# Generated by Django 4.1.7 on 2023-03-22 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("a03dd8f9-4af5-42ba-b5a0-564589cfd3ec"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("applying_position", models.CharField(max_length=100)),
                ("cv_link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("1b49b800-8658-426b-ae6d-684f4f6bb89d"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("73834730-24b8-4398-aa74-3b699f3dc26c"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interview_type", models.IntegerField()),
                (
                    "appointment_date",
                    models.DateTimeField(verbose_name="appointment date"),
                ),
                ("appointment_link", models.CharField(max_length=200)),
                ("notes", models.CharField(max_length=300)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment_app.candidate",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment_app.recruiter",
                    ),
                ),
            ],
        ),
    ]
