# Generated by Django 4.1.7 on 2023-03-22 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7c95f17a-5718-4ddf-a0ee-e66619630201"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3099f369-5ba4-459f-8b0f-9150779ab704"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8d0dca87-4b6b-490a-876f-814f5dd0c038"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
